import css from "../assets/images/css.png"
import figma from "../assets/images/figma.png"
import freeCodeCamp from "../assets/images/freeCodeCamp.png"
import github from "../assets/images/github.svg"
import hackerRank from "../assets/images/hackerRank.png"
import html from "../assets/images/html.png"
import jest from "../assets/images/jest.png"
import js from "../assets/images/js.png"
import linkedin from "../assets/images/linkedin.png"
import microverse from "../assets/images/microverse.png"
import firebase from "../assets/images/firebase.png"
import next from "../assets/images/next.png"
import postgreSQL from "../assets/images/postgreSQL.png"
import rails from "../assets/images/rails.png"
import react from "../assets/images/react.png"
import redux from "../assets/images/redux.png"
import ruby from "../assets/images/ruby.png"
import cursor from "../assets/images/cursor.png"
import mypic2 from "../assets/images/hasnatAbout2.png"
import Hasnat from "../assets/images/HasnatProfile.jpeg"
import shayan from "../assets/images/shayan.png"
import mercy from "../assets/images/mercy.jpeg"
import Abbas from "../assets/images/Abbas.jpeg"
import contactWhite from "../assets/images/contactWhite.png"
import contactimg from "../assets/images/contactimg.png"
import Gmail from "../assets/images/Gmail.svg";
import MobMenu from "../assets/images/mobMenu.png"
import blueLine from "../assets/images/blueLine.svg"
import fire from "../assets/images/fire.png"
import express from "../assets/images/express.png"
import circuit from "../assets/images/circuit.png"
import mongoDB from "../assets/images/mongoDB.png"
import arrowLeft from "../assets/images/arrow-left.svg"
import arrowRight from "../assets/images/arrow-right.svg"
import TVShow from "../assets/projectsImg/img1.png"
import housesReservation from "../assets/projectsImg/houses-reservation.png"
import leaderboard from "../assets/projectsImg/leaderboard.png"
import WeatherApp from "../assets/projectsImg/weather-App.png"
import warriorCars from "../assets/projectsImg/warriorCars.png"
import weeShareImg from "../assets/projectsImg/WeeShareImg.png"

export {
    css, figma, freeCodeCamp, github, hackerRank, html, jest, js, linkedin, microverse, firebase, next, postgreSQL, rails, react,
    redux, ruby, mypic2, cursor, shayan, mercy, Abbas, contactWhite, contactimg, Gmail, Hasnat, MobMenu, TVShow, WeatherApp, housesReservation, leaderboard, warriorCars,
    blueLine, fire, express, circuit, mongoDB, arrowLeft, arrowRight, weeShareImg
}